config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", include("core.urls", namespace="core")),
    path("rooms/", include("rooms.urls", namespace="rooms")),
    path("users/", include("users.urls", namespace="users")),
    path("admin/", admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from rooms import views as room_views

app_name = "core"

urlpatterns = [path("", room_views.HomeView.as_view(), name="home")]

users/urls.py
from django.urls import path
from . import views

app_name = "users"

urlpatterns = [
    path("login/", views.LoginView.as_view(), name="login"),
    path("logout/", views.log_out, name="logout"),
    path("signup/", views.SignupView.as_view(), name="signup"),
    path("update-profile/", views.UpdateProfileView.as_view(), name="update"),
    path("update-password/", views.UpdatePasswordView.as_view(), name="password"),
    path("<int:pk>/", views.UserProfileView.as_view(), name="profile"),
]

templates/partials/footer.html
<footer>
    &copy; Nbnb
</footer>

templates/partials/nav.html
<ul class="flex items-center text-sm font-semibold h-full">
    {% if user.is_authenticated %}
    <li class="nav_link"><a href="{{user.get_absolute_url}}">Profile</a></li>
    <li class="nav_link"><a href="{% url "users:logout" %}">Log out</a></li>
    {% else %}
    <li class="ml-8"><a href="{% url "users:login" %}">Log in</a></li>
    <li class="ml-8"><a href="{% url "users:signup" %}">Sign up</a></li>
    {% endif %}    
</ul>

templates/partials/room_card.html
<div class="w-1/4 mb-10 px-2">
    <div class="w-full h-64 bg-cover bg-center rounded-lg mb-2" style="background-image: url({{room.first_photo}});"></div>
    <div class="flex justify-between">
        <div>
            {% if room.host.superhost %}
                <span class="uppercase font-medium text-xs border border-black text-black rounded py-px px-1 mr-1">
                    superhost
                </span>
                
            {% endif %}    

            <span class="text-sm text-gray-600">
                {{room.city}}
            </span>
        </div>
        <span class="text-sm flex items-center">
            <i class="fas fa-star text-red-500 text-xs mr-1"></i> {{room.total_rating}}
        </span>
    </div>
</div>